'use client';

import { useState } from 'react';
import type {
  AppState,
  TranscriptSegment,
  CaptionTrack,
  VideoMetadata,
  TranscriptAPIResponse,
  MetadataAPIResponse,
} from '@/lib/types';
import TranscriptInput from '@/components/TranscriptInput';
import ErrorMessage from '@/components/ErrorMessage';
import VideoInfo from '@/components/VideoInfo';
import TimestampToggle from '@/components/TimestampToggle';
import LanguageSelector from '@/components/LanguageSelector';
import ActionButtons from '@/components/ActionButtons';
import TranscriptViewer from '@/components/TranscriptViewer';

export default function Home() {
  const [url, setUrl] = useState('');
  const [appState, setAppState] = useState<AppState>('idle');
  const [error, setError] = useState('');
  const [segments, setSegments] = useState<TranscriptSegment[]>([]);
  const [availableTracks, setAvailableTracks] = useState<CaptionTrack[]>([]);
  const [selectedLanguage, setSelectedLanguage] = useState('');
  const [metadata, setMetadata] = useState<VideoMetadata | null>(null);
  const [showTimestamps, setShowTimestamps] = useState(true);

  async function handleSubmit(inputUrl: string) {
    setUrl(inputUrl);
    setAppState('loading');
    setError('');
    setSegments([]);
    setAvailableTracks([]);
    setMetadata(null);

    try {
      const [transcriptRes, metadataRes] = await Promise.all([
        fetch('/api/transcript', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ url: inputUrl }),
        }),
        fetch(`/api/metadata?url=${encodeURIComponent(inputUrl)}`).catch(
          () => null
        ),
      ]);

      const transcriptData: TranscriptAPIResponse = await transcriptRes.json();

      if (!transcriptData.success) {
        setError(transcriptData.error);
        setAppState('error');
        return;
      }

      setSegments(transcriptData.data.segments);
      setAvailableTracks(transcriptData.data.availableTracks);

      // Default to first non-auto track, or first track
      const nonAutoTrack = transcriptData.data.availableTracks.find(
        (t) => !t.isAutoGenerated
      );
      setSelectedLanguage(
        nonAutoTrack?.languageCode ??
          transcriptData.data.availableTracks[0]?.languageCode ??
          ''
      );

      // Metadata is nice-to-have
      if (metadataRes && metadataRes.ok) {
        const metaData: MetadataAPIResponse = await metadataRes.json();
        if (metaData.success) {
          setMetadata(metaData.data);
        }
      }

      setAppState('success');
    } catch {
      setError('Failed to fetch transcript. Please check the URL and try again.');
      setAppState('error');
    }
  }

  async function handleLanguageChange(languageCode: string) {
    setSelectedLanguage(languageCode);
    setAppState('loading');

    try {
      const res = await fetch('/api/transcript', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url, languageCode }),
      });

      const data: TranscriptAPIResponse = await res.json();

      if (!data.success) {
        setError(data.error);
        setAppState('error');
        return;
      }

      setSegments(data.data.segments);
      setAppState('success');
    } catch {
      setError('Failed to fetch transcript for the selected language.');
      setAppState('error');
    }
  }

  return (
    <div className="flex flex-col gap-6">
      {appState === 'idle' && (
        <p className="text-muted-foreground text-sm">
          Paste a YouTube URL to extract its transcript
        </p>
      )}

      <TranscriptInput onSubmit={handleSubmit} isLoading={appState === 'loading'} />

      {appState === 'error' && error && (
        <ErrorMessage message={error} onDismiss={() => setError('')} />
      )}

      {appState === 'loading' && (
        <div className="skeleton rounded-lg" style={{ height: '60vh' }} />
      )}

      {appState === 'success' && (
        <>
          {metadata && <VideoInfo metadata={metadata} />}

          <div className="flex items-center justify-between gap-4">
            <TimestampToggle
              enabled={showTimestamps}
              onToggle={setShowTimestamps}
            />
            <LanguageSelector
              tracks={availableTracks}
              selectedLanguage={selectedLanguage}
              onLanguageChange={handleLanguageChange}
            />
          </div>

          <ActionButtons
            segments={segments}
            showTimestamps={showTimestamps}
            videoTitle={metadata?.title}
          />

          <TranscriptViewer
            segments={segments}
            showTimestamps={showTimestamps}
          />
        </>
      )}
    </div>
  );
}
