'use client';

import { CaptionTrack } from '@/lib/types';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';

interface LanguageSelectorProps {
  tracks: CaptionTrack[];
  selectedLanguage: string;
  onLanguageChange: (languageCode: string) => void;
}

export default function LanguageSelector({ tracks, selectedLanguage, onLanguageChange }: LanguageSelectorProps) {
  if (tracks.length <= 1) return null;

  return (
    <Select value={selectedLanguage} onValueChange={onLanguageChange}>
      <SelectTrigger className="w-[200px]">
        <SelectValue placeholder="Select language" />
      </SelectTrigger>
      <SelectContent>
        {tracks.map((track) => {
          const compositeKey = `${track.languageCode}-${track.isAutoGenerated ? 'auto' : 'manual'}`;
          return (
            <SelectItem key={compositeKey} value={track.languageCode}>
              {track.name}{track.isAutoGenerated ? ' (auto)' : ''}
            </SelectItem>
          );
        })}
      </SelectContent>
    </Select>
  );
}
