// TranscriptGrab — Shared TypeScript types

export interface TranscriptSegment {
  text: string;
  start: number;   // seconds (float)
  duration: number; // seconds (float)
}

export interface CaptionTrack {
  languageCode: string;
  name: string;
  baseUrl: string;
  isAutoGenerated: boolean;
}

export interface TranscriptResult {
  segments: TranscriptSegment[];
  availableTracks: CaptionTrack[];
  videoId: string;
  videoDuration?: number | null;
}

export interface VideoMetadata {
  title: string;
  author: string;
  authorUrl: string;
  thumbnailUrl: string;
}

export interface TranscriptRequest {
  url: string;
  languageCode?: string;
}

export interface TranscriptResponse {
  success: true;
  data: TranscriptResult;
}

export interface TranscriptErrorResponse {
  success: false;
  error: string;
  errorType: 'INVALID_URL' | 'NO_CAPTIONS' | 'VIDEO_UNAVAILABLE' | 'RATE_LIMITED' | 'NETWORK_ERROR' | 'UNKNOWN';
}

export type TranscriptAPIResponse = TranscriptResponse | TranscriptErrorResponse;

export interface MetadataResponse {
  success: true;
  data: VideoMetadata;
}

export interface MetadataErrorResponse {
  success: false;
  error: string;
}

export type MetadataAPIResponse = MetadataResponse | MetadataErrorResponse;

export type AppState = 'idle' | 'loading' | 'success' | 'error';
